const C=window.CURRICULUM, app=document.querySelector('#app');
const KEY='actMasteryPathway_v4';
const OLD_KEYS=['actMasteryPathway_v3','actMathPathways_v2','actMathPathways_v1'];
const STAFF_PIN='27610';
let S=JSON.parse(localStorage.getItem(KEY)||OLD_KEYS.map(k=>localStorage.getItem(k)).find(Boolean)||'null')||{name:'',view:'home',diag:null,mastered:{},module:{},post:null,seed:11,achievements:{},bookmarks:[],activity:[],settings:{reducedMotion:false}};
if(!localStorage.getItem(KEY) && S.run && ['practice','mini','post'].includes(S.run.type)) delete S.run;
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sub=id=>C.subtopics.find(x=>x.id===id);
const shuffle=(a,r=Math.random)=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function rng(seed){return()=>((seed=Math.imul(1664525,seed)+1013904223|0)>>>0)/4294967296}
function domainStats(){let out={};C.subtopics.forEach(x=>{out[x.domain]??={n:0,m:0,c:0,q:0};out[x.domain].n++;out[x.domain].m+=!!S.mastered[x.id];let d=S.diag?.bySub?.[x.id];if(d){out[x.domain].c+=d.c;out[x.domain].q+=d.n}});return out}
function recommended(){if(!S.diag)return null;return C.subtopics.filter(x=>!S.mastered[x.id]).sort((a,b)=>{let A=S.diag.bySub[a.id],B=S.diag.bySub[b.id];return (A.c/A.n)-(B.c/B.n)})[0]||null}
function shell(body){app.innerHTML=`<main class="shell"><div class="top no-print"><button class="brandButton" onclick="go('home')" aria-label="ACT Mastery Pathway home"><span class="brandMain">ACT MASTERY</span><span class="brandSub">PATHWAY</span></button><nav class="row nav" aria-label="Primary navigation"><button class="navBtn" onclick="go('home')">Dashboard</button><button class="navBtn" onclick="go('course')">Course Map</button><button class="navBtn" onclick="resources()">Toolkit</button><button class="navBtn" onclick="studyPlan()">Study Plan</button><button class="navBtn" onclick="showDataTools()">Save / Load</button><button class="navBtn staff" onclick="unlockInstructor()" title="Staff access">Staff Access</button></nav></div>${body}<footer class="footer no-print">ACT Mastery Pathway • Independent ACT-style instructional curriculum • Scores are instructional indicators, not official ACT scores.</footer></main>`;window.scrollTo(0,0)}
function unlockInstructor(){if(sessionStorage.getItem('ampStaff')==='1'){S.view='instructor';save();return render()}const pin=prompt('Enter the staff PIN:');if(pin===null)return;if(pin===STAFF_PIN){sessionStorage.setItem('ampStaff','1');S.view='instructor';save();render()}else alert('Incorrect PIN.')} 
function go(v){S.view=v;save();render()}
function home(){
 let done=C.subtopics.filter(x=>S.mastered[x.id]).length, diag=!!S.diag, all=done===C.subtopics.length, rec=recommended();
 let pct=Math.round(done/C.subtopics.length*100);
 shell(`<section class="card hero premium"><div class="eyebrow">PERSONALIZED • MASTERY-BASED • ACT-STYLE</div><div class="heroGrid"><div><div class="confetti"></div><h1>Build the math skills.<br><span>Know the strategy.</span></h1><p class="sub">Diagnostic results identify what to study next. Complete targeted lessons, demonstrate mastery, and measure growth on the post-assessment.</p><div class="row"><input class="nameinput" placeholder="Student name" value="${esc(S.name)}" oninput="S.name=this.value;save()"><span class="pill">${done}/15 subtopics mastered</span></div></div><div class="progressPanel"><div class="ring" style="--p:${pct}"><b>${pct}%</b><span>pathway complete</span></div>${diag?`<div class="miniStat"><b>${S.diag.score}/45</b><span>diagnostic</span></div>`:`<div class="miniStat"><b>45</b><span>diagnostic items</span></div>`}${S.post?`<div class="miniStat"><b>${S.post.score}/45</b><span>post-test</span></div>`:`<div class="miniStat"><b>15</b><span>skill modules</span></div>`}</div></div></section>
 <section class="card"><h2>Your pathway</h2><div class="path"><span class="${diag?'done':'active'}">1. Diagnostic</span><span class="${diag&&!all?'active':all?'done':''}">2. Personalized modules</span><span class="${all&&!S.post?'active':S.post?'done':''}">3. Post-assessment</span><span class="${S.post?'active':''}">4. Growth report</span></div>${rec?`<div class="recommend"><div><b>Recommended next:</b> ${esc(rec.name)}<div class="tiny">Based on your lowest unmastered diagnostic subtopic.</div></div><button class="btn" onclick="openModule('${rec.id}')">Continue →</button></div>`:''}</section>
 <section class="grid featureGrid">
 <div class="card"><div class="icon"></div><h3>Diagnostic</h3><p class="sub">45 original ACT-style questions • 50 minutes • balanced across 15 subtopics.</p>${S.diag?`<p><b>${S.diag.score}/45</b> correct</p><button class="btn secondary" onclick="startTest('diag',true)">Retake diagnostic</button>`:`<button class="btn" onclick="startTest('diag')">Begin diagnostic</button>`}</div>
 <div class="card"><div class="icon"></div><h3>Personalized learning path</h3><p class="sub">Skills demonstrated on the diagnostic are marked complete. Remaining topics become focused lessons with strategy-first practice.</p><button class="btn" ${diag?'':'disabled'} onclick="go('modules')">Open my modules</button></div>
 <div class="card"><div class="icon"></div><h3>Post-assessment</h3><p class="sub">A parallel 45-question form measures transfer after all modules are mastered.</p><button class="btn" ${all?'':'disabled'} onclick="startTest('post')">${S.post?'Retake':'Begin'} post-assessment</button></div>
 <div class="card"><div class="icon"></div><h3>Mastery report</h3><p class="sub">Printable diagnostic-to-post growth with subtopic-level evidence.</p><button class="btn secondary" onclick="report()">View report</button></div></section>
 <section class="grid featureGrid"><div class="card"><div class="icon"></div><h3>Study plan</h3><p class="sub">Turn diagnostic data into a prioritized week-by-week plan with estimated module time.</p><button class="btn secondary" onclick="studyPlan()">Build my plan</button></div><div class="card"><div class="icon"></div><h3>Math toolkit</h3><p class="sub">ACT-focused formulas, vocabulary, test-day habits, and quick-reference strategy cards.</p><button class="btn secondary" onclick="resources()">Open toolkit</button></div><div class="card"><div class="icon"></div><h3>Completion certificate</h3><p class="sub">After the post-assessment, print a polished record of curriculum completion and growth.</p><button class="btn secondary" ${S.post?'':'disabled'} onclick="certificate()">View certificate</button></div></section>
 <section class="card"><div class="row"><div><div class="eyebrow">WHAT MAKES THIS DIFFERENT</div><h2>Strategy is assessed before computation.</h2></div></div><div class="grid"><div class="callout"><b>1 • Recognize</b><span>Students identify the mathematical approach.</span></div><div class="callout"><b>2 • Reason</b><span>Feedback corrects misconceptions without revealing the answer.</span></div><div class="callout"><b>3 • Execute</b><span>Students independently solve the ACT-style problem.</span></div><div class="callout"><b>4 • Prove mastery</b><span>A 5-item unscaffolded check requires 80%.</span></div></div></section>`)
}
function courseMap(){let groups={};C.subtopics.forEach(x=>(groups[x.domain]??=[]).push(x));let html=Object.entries(groups).map(([d,xs])=>`<section class="card"><div class="row"><h2>${esc(d)}</h2><span class="spacer"></span><span class="pill">${xs.filter(x=>S.mastered[x.id]).length}/${xs.length} mastered</span></div><div class="curriculumList">${xs.map((x,i)=>`<button class="curriculumRow" onclick="${S.diag?`openModule('${x.id}')`:`go('home')`}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><b>${esc(x.name)}</b><small>${esc(x.desc)}</small></span><span>${S.mastered[x.id]?'✓':'→'}</span></button>`).join('')}</div></section>`).join('');shell(`<section class="card"><div class="eyebrow">SCOPE & SEQUENCE</div><h1>ACT Math Course Map</h1><p class="sub">Fifteen measurable subtopics organized into a focused sequence. Diagnostic mastery allows students to move past content they can already demonstrate independently.</p></section>${html}`)}
function modules(){
 if(!S.diag)return go('home');
 let cards=C.subtopics.map((x,i)=>{let m=S.mastered[x.id], ds=S.diag.bySub[x.id]||{c:0,n:3}, ms=S.module[x.id]||{};let status=m?'mastered':ms.practiceDone?'assessment ready':'instruction';return `<div class="card module ${m?'mastered':''}"><div class="row"><span class="tag">${esc(x.domain)}</span><span class="spacer"></span><span class="status ${status}">${m?'✓ Mastered':ms.practiceDone?'Ready to prove':'Learn'}</span></div><h3>${esc(x.name)}</h3><p class="sub">${esc(x.desc)}</p><div class="skillMeter"><i style="width:${ds.c/ds.n*100}%"></i></div><p class="tiny">Diagnostic evidence: ${ds.c}/${ds.n} • ${m&&ms.source==='diagnostic'?'compacted from diagnostic':ms.attempts?`best mastery check ${ms.best}/5`:'module assigned'}</p><button class="btn ${m?'secondary':''}" onclick="openModule('${x.id}')">${m?'Review':'Open module'} →</button></div>`}).join('');
 shell(`<section class="card"><div class="eyebrow">YOUR PERSONALIZED PLAN</div><h1>Mastery modules</h1><p class="sub">Green modules are complete. Unfinished modules move from explicit modeling to guided strategy practice and finally to an unscaffolded five-question mastery check.</p><div class="legend"><span>Learn</span><span>Assessment ready</span><span>✓ Mastered</span></div></section><section class="grid">${cards}</section>`)
}
function openModule(id){S.current=id;S.view='module';save();renderModule()}
function renderModule(){let x=sub(S.current), ms=S.module[x.id]||{}, d=S.diag?.bySub?.[x.id];let traps={num_frac:'Watch units and preserve the order of ratios.',num_pct:'Distinguish “percent of” from “percent change.”',alg_linear:'Apply every operation to both sides of the equation.',alg_expr:'Exponent rules apply to matching bases—not to addition.',alg_quad:'After factoring, set each factor equal to zero.',func:'The value inside parentheses is the input, not multiplication.',lines:'Keep slope and y-intercept in their correct positions.',stats:'A mean is based on the total and the number of values.',prob:'The denominator must represent the full sample space.',geo_area:'Decide whether the question asks for length, area, or volume.',geo_coord:'Average coordinates for midpoint; use differences for distance.',geo_tri:'Identify the hypotenuse before using the Pythagorean theorem.',trig:'Opposite and adjacent depend on the reference angle.',poly:'Area scales by the square of a linear scale factor.',advanced:'Simplify structure before approximating decimals.'};shell(`<section class="card moduleHero"><div class="row"><span class="tag">${esc(x.domain)}</span><span class="spacer"></span><span class="pill">${S.mastered[x.id]?'✓ mastered':'assigned module'}</span></div><h1>${esc(x.name)}</h1><p class="sub">${esc(x.desc)}</p>${d?`<div class="evidence">Diagnostic evidence <b>${d.c}/${d.n}</b> • Mastery target <b>80%</b></div>`:''}</section>
<section class="lessonGrid"><section class="card"><div class="lessonNo">01</div><h2>Learn it</h2><h3>Worked example</h3><div class="qstem">${esc(x.example[0])}</div><div class="feedback">${esc(x.example[1])}</div><h3>Strategy to remember</h3><p class="sub">${esc(x.strategy[0])}</p></section><section class="card"><div class="lessonNo">02</div><h2>ACT lens</h2><div class="trap"><b>⚠ Common trap</b><p>${esc(traps[x.id])}</p></div><div class="tip"><b>⏱ Test-day habit</b><p>Before calculating, name what the question is asking for and estimate what a reasonable answer should look like.</p></div><div class="tip"><b>🧠 Mastery target</b><p>You should be able to recognize the method without a hint and execute it accurately.</p></div></section></section>
<section class="card"><div class="row"><div><div class="lessonNo">03</div><h2>Guided practice</h2><p class="sub">Three problems use a two-step routine: choose the strategy first, then solve. Strategy feedback teaches the method without disclosing the answer.</p></div><span class="spacer"></span><span class="pill">${ms.practiceDone?'✓ practice complete':'3 questions'}</span></div><button class="btn" onclick="startPractice('${x.id}')">${ms.practiceDone?'Practice again':'Start guided practice'} →</button></section>
<section class="card masteryGate"><div><div class="lessonNo">04</div><h2>Prove mastery</h2><p class="sub">Five fresh, unscaffolded questions. Score 4/5 or better. Retakes use new values so completion reflects the skill—not memorization.</p>${ms.attempts?`<p class="tiny">Attempts: ${ms.attempts} • Best: ${ms.best||0}/5</p>`:''}</div><button class="btn" ${ms.practiceDone?'':'disabled'} onclick="startMini('${x.id}')">${S.mastered[x.id]?'Retake check':'Take mastery check'} →</button></section>`)}
function instructorView(){let stats=domainStats(), done=C.subtopics.filter(x=>S.mastered[x.id]).length;let rows=Object.entries(stats).map(([d,z])=>`<tr><td>${esc(d)}</td><td>${z.q?z.c+'/'+z.q:'—'}</td><td>${z.m}/${z.n}</td><td>${z.n?Math.round(z.m/z.n*100):0}%</td></tr>`).join('');shell(`<section class="card"><div class="eyebrow">INSTRUCTOR PREVIEW</div><h1>Instructional dashboard</h1><p class="sub">This static GitHub edition summarizes the student currently using this browser. A licensed production edition should connect the same data model to secure student accounts and a center-wide roster dashboard.</p></section><section class="grid"><div class="stat card"><div class="tiny">Student</div><div class="big">${esc(S.name||'Demo student')}</div></div><div class="stat card"><div class="tiny">Diagnostic</div><div class="big">${S.diag?S.diag.score+'/45':'—'}</div></div><div class="stat card"><div class="tiny">Mastered</div><div class="big">${done}/15</div></div><div class="stat card"><div class="tiny">Post</div><div class="big">${S.post?S.post.score+'/45':'—'}</div></div></section><section class="card"><h2>Domain evidence</h2><table><thead><tr><th>Domain</th><th>Diagnostic</th><th>Subtopics mastered</th><th>Completion</th></tr></thead><tbody>${rows}</tbody></table></section><section class="card"><h2>Learning-process analytics</h2>${(()=>{let a=strategyAnalytics();let attempts=Object.values(S.module||{}).reduce((n,m)=>n+(m.attempts||0),0);return `<div class="grid"><div class="stat"><div class="tiny">Strategy accuracy</div><div class="big">${a.n?a.pct+'%':'—'}</div><div class="tiny">${a.ok}/${a.n} guided decisions</div></div><div class="stat"><div class="tiny">Mastery attempts</div><div class="big">${attempts}</div></div><div class="stat"><div class="tiny">Modules compacted</div><div class="big">${C.subtopics.filter(x=>S.module[x.id]?.source==='diagnostic').length}</div></div><div class="stat"><div class="tiny">Modules learned</div><div class="big">${C.subtopics.filter(x=>S.module[x.id]?.source==='module').length}</div></div></div>`})()}</section><section class="card"><h2>Production center dashboard roadmap</h2><div class="grid"><div class="callout"><b>Roster + cohorts</b><span>Students grouped by tutor, class, site, and term.</span></div><div class="callout"><b>Assignment controls</b><span>Assign modules, deadlines, retakes, and targeted intervention.</span></div><div class="callout"><b>Analytics</b><span>Strategy errors vs. execution errors, time-on-task, attempts, and growth.</span></div><div class="callout"><b>License administration</b><span>Center seats, renewal dates, usage reporting, and branded reports.</span></div></div></section>`)}
// -------- Original question generators --------
function makeQ(id,seed,kind='practice'){let r=rng(seed), R=(a,b)=>Math.floor(r()*(b-a+1))+a, pick=a=>a[Math.floor(r()*a.length)], A=[], stem='', ans=0, exp='', visual='';
 const mc=(correct,wrong)=>{let raw=[correct,...wrong].map(String);if(new Set(raw).size!==5) throw new Error(`Duplicate answer choices generated for ${id} (seed ${seed}): ${raw.join(' | ')}`);let vals=shuffle(raw,r);ans=vals.indexOf(String(correct));return vals};
 switch(id){
 case'num_frac':{let b=pick([3,4,5,6,8]), k=R(2,5), unit=R(2,7), total=b*k, target=unit*k; stem=`A machine uses ${unit} liters of coolant for every ${b} hours of operation. At the same rate, how many liters are used in ${total} hours?`;A=mc(target,[target+1,target-1,target+2,target-2]);exp=`The rate is ${unit}/${b} liter per hour. Scaling ${b} hours to ${total} hours multiplies by ${k}, so the coolant amount scales by the same factor.`;break}
 case'num_pct':{let whole=R(4,12)*25,p=pick([10,20,25,30,40,60]),correct=whole*p/100;stem=`What is ${p}% of ${whole}?`;A=mc(correct,[correct+10,correct+5,Math.max(0,correct-10),whole]);exp=`Convert ${p}% to ${p/100} and multiply by ${whole}.`;break}
 case'alg_linear':{let x=R(2,12),a=R(2,7),b=R(1,12),c=a*x+b;stem=`If ${a}x + ${b} = ${c}, what is x?`;A=mc(x,[x+1,x-1,x+2,x+3]);exp=`Undo the +${b}, then divide by ${a}.`;break}
 case'alg_expr':{let a=R(2,6),b=R(2,5),m=R(2,5),n=R(2,5),coef=a*b,pow=m+n;stem=`Simplify ${a}x<sup>${m}</sup> · ${b}x<sup>${n}</sup>.`;A=mc(`${coef}x^${pow}`,[`${coef+1}x^${pow}`,`${coef}x^${pow+1}`,`${coef}x^${Math.max(1,pow-1)}`,`${Math.max(1,coef-1)}x^${pow+2}`]);exp=`Multiply coefficients (${a}·${b}) and add exponents on the common base x (${m}+${n}).`;break}
 case'alg_quad':{let u=R(2,7),v=R(2,8),sum=u+v,prod=u*v;stem=`Which value is a solution of x² - ${sum}x + ${prod} = 0?`;A=mc(u,[u-1,u+1,u+2,u+3]);exp=`Look for two numbers whose sum is ${sum} and product is ${prod}; those numbers determine the factors.`;break}
 case'func':{let a=R(2,5),b=R(-6,6),x=R(2,7),correct=a*x+b;stem=`If f(x) = ${a}x ${b>=0?'+ '+b:'- '+Math.abs(b)}, what is f(${x})?`;A=mc(correct,[correct+a,correct-a,correct+1,correct-1]);exp=`Substitute ${x} for x everywhere in the rule, then follow order of operations.`;break}
 case'lines':{let m=pick([-4,-3,-2,2,3,4]),b=R(-6,6),fmt=(mm,bb)=>`y = ${mm}x ${bb>=0?'+ '+bb:'- '+Math.abs(bb)}`;stem=`Which equation has slope ${m} and y-intercept ${b}?`;A=mc(fmt(m,b),[fmt(-m,b),fmt(m,b+1),fmt(m,b-1),fmt(-m,b+2)]);exp=`In y=mx+b, m is the slope and b is the y-intercept.`;break}
 case'stats':{let vals=[R(60,80),R(70,90),R(75,95),R(65,90)],mean=R(75,90),need=mean*5-vals.reduce((a,b)=>a+b,0);while(need<50||need>110){mean=R(75,90);need=mean*5-vals.reduce((a,b)=>a+b,0)}stem=`Four scores are ${vals.join(', ')}. What fifth score gives a mean of ${mean}?`;A=mc(need,[need+2,need-2,need+4,need-4]);exp=`A mean of ${mean} across 5 scores requires a total of ${mean*5}. Subtract the sum of the four known scores.`;break}
 case'prob':{let red=R(2,7),blue=R(2,7),green=R(1,5),tot=red+blue+green,correct=`${red}/${tot}`;stem=`A bag contains ${red} red, ${blue} blue, and ${green} green tokens. What is the probability of selecting a red token?`;A=mc(correct,[`${red+1}/${tot}`,`${red}/${tot+1}`,`${Math.max(1,red-1)}/${tot}`,`${red+blue}/${tot}`]);exp=`Probability is favorable outcomes over total outcomes: count red tokens, then count all tokens.`;break}
 case'geo_area':{let l=R(6,18),w=R(4,12),correct=2*(l+w);stem=`A rectangular patio measures ${l} ft by ${w} ft. How many feet of edging are needed around the patio?`;A=mc(correct,[l*w,l+w,2*l*w,correct+2]);exp=`“Around” asks for perimeter, so use 2l+2w rather than area.`;break}
 case'geo_coord':{let x1=R(-6,2)*2,y1=R(-5,3)*2,x2=x1+R(2,6)*2,y2=y1+R(2,6)*2,cx=(x1+x2)/2,cy=(y1+y2)/2;stem=`What is the midpoint of (${x1}, ${y1}) and (${x2}, ${y2})?`;A=mc(`(${cx}, ${cy})`,[`(${cx+1}, ${cy})`,`(${cx-1}, ${cy})`,`(${cx}, ${cy+1})`,`(${cx}, ${cy-1})`]);exp=`Average the two x-coordinates and separately average the two y-coordinates.`;break}
 case'geo_tri':{let triples=pick([[3,4,5],[5,12,13],[8,15,17],[7,24,25]]),k=R(1,3),a=triples[0]*k,b=triples[1]*k,c=triples[2]*k;stem=`A right triangle has legs ${a} and ${b}. What is its hypotenuse?`;A=mc(c,[c-1,c+1,a+b,Math.abs(b-a)]);exp=`The unknown is the hypotenuse, so use a²+b²=c² with the two given legs.`;visual=`<svg class="diagram" viewBox="0 0 260 150"><polyline points="35,125 210,125 210,35 35,125" fill="none" stroke="currentColor" stroke-width="3"/><rect x="196" y="111" width="14" height="14" fill="none" stroke="currentColor"/><text x="110" y="145">${a}</text><text x="218" y="82">${b}</text><text x="105" y="70">?</text></svg>`;break}
 case'trig':{let tri=pick([[3,4,5],[5,12,13],[8,15,17]]),opp=tri[0],adj=tri[1],hyp=tri[2];stem=`In a right triangle, relative to angle θ, the opposite side is ${opp} and the hypotenuse is ${hyp}. Which ratio gives sin θ?`;A=mc(`${opp}/${hyp}`,[`${adj}/${hyp}`,`${opp}/${adj}`,`${hyp}/${opp}`,`${hyp}/${adj}`]);exp=`Label sides relative to θ. Sine is opposite/hypotenuse (SOH). Do not evaluate the ratio until after choosing the relationship.`;break}
 case'poly':{let n=pick([5,6,8,9,10,12]),correct=(n-2)*180/n;stem=`A regular ${n}-gon has equal interior angles. What is the measure of one interior angle?`;A=mc(`${correct}°`,[`${360/n}°`,`${correct-10}°`,`${correct+10}°`,`${correct+20}°`]);exp=`First find the interior-angle sum, (n−2)·180°, then divide by n because the polygon is regular.`;break}
 case'advanced':{let roots=pick([[12,2,3],[20,2,5],[27,3,3],[45,3,5],[75,5,3],[98,7,2]]),N=roots[0],co=roots[1],inside=roots[2];stem=`Simplify √${N}.`;A=mc(`${co}√${inside}`,[`${co-1}√${inside}`,`${co+1}√${inside}`,`${co}√${inside+1}`,`${co*inside}`]);exp=`Factor ${N} into a perfect square times a remaining factor, then take the square root of the perfect square.`;break}
 }
 return {id:`${id}-${seed}`,sub:id,stem,choices:A,answer:ans,explain:exp,visual};}

function startPractice(id){S.run={type:'practice',sub:id,i:0,qs:[0,1,2].map(k=>makeQ(id,S.seed++ + k*101)),answers:[],strategy:[]};save();renderPractice()}
function renderPractice(){let R=S.run,q=R.qs[R.i],x=sub(R.sub), st=x.strategy, state=R.strategy[R.i];let strategyChoices=st[1];shell(`<section class="card"><div class="row"><span class="tag">Guided practice ${R.i+1}/3</span><span class="spacer"></span><span>${esc(x.name)}</span></div><div class="progress"><i style="width:${R.i/3*100}%"></i></div></section><section class="card"><h2>Step 1 • Choose a strategy</h2><div class="qstem">${q.stem}</div>${q.visual||''}<p class="sub">Which approach should you use? You are choosing a method—not solving yet.</p>${strategyChoices.map((c,i)=>`<button class="choice ${state!==undefined?(i===x.strategyCorrect?'correct':i===state&&state!==x.strategyCorrect?'wrong':''):''}" ${state!==undefined?'disabled':''} onclick="pickStrategy(${i})">${esc(c)}</button>`).join('')}${state!==undefined?`<div class="feedback ${state===x.strategyCorrect?'good':'bad'}"><b>${state===x.strategyCorrect?'✓ Good strategy':'Not quite — use this strategy:'}</b> ${esc(st[0])}<br><span class="tiny">Notice that this explains the approach without giving away the answer.</span></div><button class="btn" onclick="renderSolve()">Now solve it →</button>`:''}</section>`)}
function pickStrategy(i){let x=sub(S.run.sub);S.run.strategy[S.run.i]=i;S.activity=S.activity||[];S.activity.push({t:Date.now(),type:'strategy',sub:S.run.sub,correct:i===x.strategyCorrect});save();renderPractice()}
function renderSolve(){let R=S.run,q=R.qs[R.i],chosen=R.answers[R.i];shell(`<section class="card"><span class="tag">Step 2 • Solve</span><div class="qstem">${q.stem}</div>${q.visual||''}${q.choices.map((c,i)=>`<button class="choice ${chosen!==undefined?(i===q.answer?'correct':i===chosen&&chosen!==q.answer?'wrong':''):''}" ${chosen!==undefined?'disabled':''} onclick="pickPracticeAnswer(${i})">${String.fromCharCode(65+i)}. ${c}</button>`).join('')}${chosen!==undefined?`<div class="feedback ${chosen===q.answer?'good':'bad'}"><b>${chosen===q.answer?'✓ Correct!':'Correct answer: '+String.fromCharCode(65+q.answer)}</b><br>${q.explain}</div><button class="btn" onclick="nextPractice()">${R.i===2?'Finish practice':'Next question'} →</button>`:''}</section>`)}
function pickPracticeAnswer(i){let q=S.run.qs[S.run.i];S.run.answers[S.run.i]=i;S.activity=S.activity||[];S.activity.push({t:Date.now(),type:'practice',sub:S.run.sub,correct:i===q.answer});save();renderSolve()}
function nextPractice(){if(S.run.i<2){S.run.i++;save();renderPractice()}else{let id=S.run.sub;S.module[id]=S.module[id]||{};S.module[id].practiceDone=true;save();S.current=id;renderModule()}}
function startMini(id){let attempt=(S.module[id]?.attempts||0)+1;S.run={type:'mini',sub:id,i:0,qs:[0,1,2,3,4].map(k=>makeQ(id,S.seed++ + k*173+attempt*997)),answers:[]};save();renderMini()}
function renderMini(){let R=S.run,q=R.qs[R.i],chosen=R.answers[R.i];shell(`<section class="card"><div class="row"><span class="tag">Mastery check</span><span class="spacer"></span><b>${R.i+1}/5</b></div><div class="progress"><i style="width:${R.i/5*100}%"></i></div><div class="qstem">${q.stem}</div>${q.visual||''}${q.choices.map((c,i)=>`<button class="choice" ${chosen!==undefined?'disabled':''} onclick="pickMini(${i})">${String.fromCharCode(65+i)}. ${c}</button>`).join('')}${chosen!==undefined?`<button class="btn" onclick="nextMini()">${R.i===4?'Submit mastery check':'Next'} →</button>`:''}</section>`)}
function pickMini(i){let q=S.run.qs[S.run.i];S.run.answers[S.run.i]=i;S.activity=S.activity||[];S.activity.push({t:Date.now(),type:'mastery_item',sub:S.run.sub,correct:i===q.answer});save();renderMini()}
function nextMini(){let R=S.run;if(R.i<4){R.i++;save();renderMini();return}let score=R.answers.reduce((n,a,i)=>n+(a===R.qs[i].answer),0),id=R.sub;S.module[id]=S.module[id]||{};S.module[id].attempts=(S.module[id].attempts||0)+1;S.module[id].last=score;S.module[id].best=Math.max(S.module[id].best||0,score);if(score>=4){S.mastered[id]=true;S.module[id].source='module'}save();shell(`<section class="card hero"><div class="confetti">${score>=4?'🌸 ✦ 🌷 ✦ 🌸':'🌱 ✦ 🌱'}</div><h1>${score>=4?'Module mastered!':'Almost there.'}</h1><p class="sub">You scored <b>${score}/5</b>. ${score>=4?'That meets the 80% mastery target. This subtopic is now complete.':'You need 4/5 to complete the module. Review the example and try a fresh version.'}</p><div class="row"><button class="btn" onclick="go('modules')">Back to modules</button>${score>=4&&C.subtopics.filter(x=>S.mastered[x.id]).length%3===0?'<button class="btn secondary" onclick="brainBreak()">🧠 Take a brain break</button>':''}<button class="btn secondary" onclick="openModule('${id}')">${score>=4?'Review':'Try again'}</button></div></section>`)}

function makePost(){let qs=[];C.subtopics.forEach((x,si)=>{for(let k=0;k<3;k++)qs.push(makeQ(x.id,70000+si*1009+k*131,'post'))});return shuffle(qs,rng(424242))}
function startTest(type,retake=false){if(type==='post'&&C.subtopics.some(x=>!S.mastered[x.id]))return;let qs=type==='diag'?shuffle(C.diagnostic,rng(31337)):makePost();S.run={type,i:0,qs,answers:Array(qs.length),started:Date.now(),remaining:3000};save();renderTest()}
let timerHandle=null;
function renderTest(){clearInterval(timerHandle);let R=S.run,q=R.qs[R.i],chosen=R.answers[R.i];R.flagged=R.flagged||[];let answered=R.answers.filter(x=>x!==undefined).length;let nav=R.qs.map((_,i)=>`<button class="qnav ${R.answers[i]!==undefined?'answered':''} ${R.flagged.includes(i)?'flagged':''} ${i===R.i?'current':''}" onclick="jumpTest(${i})">${i+1}</button>`).join('');shell(`<section class="card"><div class="row"><span class="tag">${R.type==='diag'?'Diagnostic':'Post-assessment'}</span><span class="spacer"></span><b>Question ${R.i+1} of 45</b><span class="pill" id="timer">50:00</span></div><div class="progress"><i style="width:${answered/45*100}%"></i></div><p class="tiny">${answered}/45 answered • ${R.flagged.length} flagged for review • progress autosaves in this browser</p></section><section class="testLayout"><section class="card"><div class="qstem">${q.stem}</div>${q.visual||''}${q.choices.map((c,i)=>`<button class="choice ${chosen===i?'selected':''}" onclick="pickTest(${i})">${String.fromCharCode(65+i)}. ${c}</button>`).join('')}<div class="row"><button class="btn secondary" onclick="toggleFlag()">${R.flagged.includes(R.i)?'★ Flagged':'☆ Flag for review'}</button><span class="spacer"></span><button class="btn secondary" ${R.i===0?'disabled':''} onclick="testNav(-1)">← Back</button><button class="btn" onclick="testNav(1)">${R.i===44?'Review & submit':'Next →'}</button></div></section><aside class="card testNav"><h3>Question navigator</h3><div class="qgrid">${nav}</div><div class="legend"><span>● answered</span><span>★ flagged</span></div>${R.i===44?`<button class="btn" onclick="reviewTest()">Review test</button>`:''}</aside></section><section class="card tiny">Diagnostic and post-assessment questions intentionally do not provide immediate correctness feedback so the scores remain useful as assessment data.</section>`);tick();timerHandle=setInterval(tick,1000)}
function jumpTest(i){S.run.i=i;save();renderTest()}
function toggleFlag(){let R=S.run;R.flagged=R.flagged||[];let i=R.flagged.indexOf(R.i);if(i>=0)R.flagged.splice(i,1);else R.flagged.push(R.i);save();renderTest()}
function reviewTest(){let R=S.run,un=R.answers.map((a,i)=>a===undefined?i:null).filter(x=>x!==null);shell(`<section class="card"><div class="eyebrow">FINAL REVIEW</div><h1>Check your work before submitting</h1><p class="sub">You have answered <b>${45-un.length}/45</b> questions. ${un.length?`There are <b>${un.length}</b> unanswered questions.`:'Every question has an answer.'}</p>${un.length?`<div class="notice">Unanswered: ${un.map(i=>`<button class="btn secondary" onclick="jumpTest(${i})">${i+1}</button>`).join(' ')}</div>`:''}<p>Flagged for review: ${R.flagged?.length?R.flagged.map(i=>`<button class="btn secondary" onclick="jumpTest(${i})">${i+1}</button>`).join(' '):'None'}</p><div class="row"><button class="btn secondary" onclick="renderTest()">Return to test</button><button class="btn" onclick="confirmSubmit()">Submit assessment</button></div></section>`)}
function confirmSubmit(){let un=S.run.answers.filter(x=>x===undefined).length;if(un&&!confirm(`You still have ${un} unanswered question${un===1?'':'s'}. Submit anyway?`))return;finishTest()}
function tick(){let R=S.run;if(!R||!['diag','post'].includes(R.type))return;let sec=Math.max(0,3000-Math.floor((Date.now()-R.started)/1000)),el=document.querySelector('#timer');if(el)el.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(sec===0){clearInterval(timerHandle);finishTest()}}
function pickTest(i){S.run.answers[S.run.i]=i;save();renderTest()}
function testNav(d){let R=S.run;if(d>0&&R.i===44){reviewTest();return}R.i=Math.max(0,Math.min(44,R.i+d));save();renderTest()}
function finishTest(){clearInterval(timerHandle);let R=S.run,score=0,by={};C.subtopics.forEach(x=>by[x.id]={c:0,n:0});R.qs.forEach((q,i)=>{let ok=R.answers[i]===q.answer;score+=ok;by[q.sub].n++;by[q.sub].c+=ok});let result={score,bySub:by,date:new Date().toISOString()};if(R.type==='diag'){S.diag=result;C.subtopics.forEach(x=>{let z=by[x.id];if(z.n&&z.c/z.n>=.8){S.mastered[x.id]=true;S.module[x.id]={...(S.module[x.id]||{}),source:'diagnostic'}}else if(S.module[x.id]?.source==='diagnostic'){delete S.mastered[x.id];delete S.module[x.id]}})}else S.post=result;save();shell(`<section class="card hero"><div class="confetti">✦ 🌷 </div><h1>${R.type==='diag'?'Diagnostic complete':'Post-assessment complete'}</h1><p class="sub">Score: <b>${score}/45 (${Math.round(score/45*100)}%)</b>.</p><button class="btn" onclick="${R.type==='diag'?"go('modules')":"report()"}">${R.type==='diag'?'See my personalized pathway':'View growth report'}</button></section>`)}

function report(){let rows=C.subtopics.map(x=>{let d=S.diag?.bySub[x.id],p=S.post?.bySub[x.id],m=S.mastered[x.id];return `<tr><td>${esc(x.domain)}</td><td>${esc(x.name)}</td><td>${d?d.c+'/'+d.n:'—'}</td><td>${m?'✓ Mastered':'Not yet'}</td><td>${p?p.c+'/'+p.n:'—'}</td></tr>`}).join('');let growth=S.diag&&S.post?S.post.score-S.diag.score:null;shell(`<section class="card report"><div class="row"><div><h1>ACT Mastery Pathway • Mastery Report</h1><p><b>Student:</b> ${esc(S.name||'________________')}</p></div><span class="spacer"></span><button class="btn no-print" onclick="window.print()">Print report</button>${S.post?'<button class="btn secondary no-print" onclick="certificate()"> Certificate</button>':''}</div><div class="grid"><div class="stat"><div class="tiny">Diagnostic</div><div class="big">${S.diag?S.diag.score+'/45':'—'}</div></div><div class="stat"><div class="tiny">Modules mastered</div><div class="big">${C.subtopics.filter(x=>S.mastered[x.id]).length}/15</div></div><div class="stat"><div class="tiny">Post-assessment</div><div class="big">${S.post?S.post.score+'/45':'—'}</div></div><div class="stat"><div class="tiny">Raw-score growth</div><div class="big">${growth===null?'—':(growth>=0?'+':'')+growth}</div></div></div><h2>Subtopic detail</h2><table><thead><tr><th>Domain</th><th>Subtopic</th><th>Diagnostic</th><th>Status</th><th>Post</th></tr></thead><tbody>${rows}</tbody></table><p class="tiny">Mastery rule: ≥80%. Diagnostic has 3 items per subtopic, so 3/3 is required for diagnostic pre-mastery. Module mastery checks require 4/5. Scores are instructional indicators, not official ACT scores.</p></section>`)}
function strategyAnalytics(){let a=(S.activity||[]).filter(x=>x.type==='strategy'),ok=a.filter(x=>x.correct).length;return {n:a.length,ok,pct:a.length?Math.round(ok/a.length*100):0}}
function studyPlan(){if(!S.diag){shell(`<section class="card"><h1> Personalized study plan</h1><p class="sub">Complete the diagnostic first. Your plan will prioritize the weakest unmastered subtopics and remove skills you have already demonstrated.</p><button class="btn" onclick="startTest('diag')">Begin diagnostic</button></section>`);return}let remaining=C.subtopics.filter(x=>!S.mastered[x.id]).sort((a,b)=>{let A=S.diag.bySub[a.id],B=S.diag.bySub[b.id];return A.c/A.n-B.c/B.n}),mins=remaining.reduce((n,x)=>n+(x.estimatedMinutes||18),0),weeks=Math.max(1,Math.ceil(mins/90));let rows=remaining.map((x,i)=>{let d=S.diag.bySub[x.id];return `<tr><td>${i+1}</td><td><b>${esc(x.name)}</b><br><span class="tiny">${esc(x.domain)}</span></td><td>${d.c}/${d.n}</td><td>${x.estimatedMinutes||18} min</td><td><button class="btn secondary" onclick="openModule('${x.id}')">Open</button></td></tr>`}).join('');shell(`<section class="card hero"><div class="eyebrow">DATA-DRIVEN PLAN</div><h1> ${esc(S.name||'Your')} study plan</h1><p class="sub">${remaining.length?`${remaining.length} modules remain • about ${mins} focused minutes • approximately ${weeks} week${weeks===1?'':'s'} at 90 minutes/week.`:'All instructional modules are mastered. You are ready for the post-assessment.'}</p></section><section class="card"><h2>Recommended sequence</h2>${remaining.length?`<table><thead><tr><th>Priority</th><th>Subtopic</th><th>Diagnostic</th><th>Est. time</th><th></th></tr></thead><tbody>${rows}</tbody></table>`:`<button class="btn" onclick="startTest('post')">Begin post-assessment</button>`}</section><section class="card"><h2>Suggested weekly routine</h2><div class="grid"><div class="callout"><b>Session A • Learn</b><span>Worked example + ACT lens + guided strategy practice.</span></div><div class="callout"><b>Session B • Retrieve</b><span>Return without notes and complete the 5-item mastery check.</span></div><div class="callout"><b>Session C • Spiral</b><span>Review one mastered module plus the next priority skill.</span></div></div></section>`)}
function resources(){let formulas=[['Percent','part = percent × whole'],['Slope','m = (y₂ − y₁)/(x₂ − x₁)'],['Midpoint','((x₁+x₂)/2, (y₁+y₂)/2)'],['Distance','√((x₂−x₁)² + (y₂−y₁)²)'],['Pythagorean theorem','a² + b² = c²'],['Rectangle','A = lw • P = 2l + 2w'],['Triangle area','A = ½bh'],['Circle','C = 2πr • A = πr²'],['Rectangular prism','V = lwh'],['Cylinder','V = πr²h'],['Polygon interior sum','(n − 2)180°'],['Trig','sin = O/H • cos = A/H • tan = O/A'],['Quadratic formula','x = (−b ± √(b²−4ac))/(2a)'],['Probability','favorable outcomes / total outcomes']];shell(`<section class="card hero"><div class="eyebrow">STUDENT TOOLKIT</div><h1> ACT Math quick reference</h1><p class="sub">A concise reference for learning and review. Do not use it during a diagnostic, mastery check, or post-assessment unless your testing plan explicitly allows references.</p></section><section class="card"><h2>High-utility formulas</h2><div class="formulaGrid">${formulas.map(([a,b])=>`<div class="formula"><b>${a}</b><span>${b}</span></div>`).join('')}</div></section><section class="card"><h2>Strategy cards</h2><div class="grid">${C.subtopics.map(x=>`<div class="callout"><b>${esc(x.name)}</b><span>${esc(x.strategy[0])}</span></div>`).join('')}</div></section><section class="card"><h2>ACT habits that transfer</h2><div class="grid"><div class="callout"><b>Translate before calculating</b><span>Write what the question is asking for and attach units.</span></div><div class="callout"><b>Estimate first</b><span>A rough range can eliminate implausible answer choices.</span></div><div class="callout"><b>Use answer choices strategically</b><span>Backsolve when choices are numeric and direct algebra is cumbersome.</span></div><div class="callout"><b>Move, mark, return</b><span>Flag a time-consuming item and protect time for accessible questions.</span></div><div class="callout"><b>Check representation</b><span>Tables, graphs, diagrams, and equations each encode different information.</span></div><div class="callout"><b>Calculator with purpose</b><span>Use it to reduce arithmetic load—not to replace mathematical setup.</span></div></div></section>`)}
function brainBreak(){let cards=[['y = mx + b','slope-intercept form'],['a² + b² = c²','right triangles'],['sin θ = O/H','sine ratio'],['A = πr²','circle area'],['P(A)','probability notation'],['f(x)','function output']];cards=shuffle(cards,rng(S.seed++));shell(`<section class="card hero"><div class="confetti">🌷 ✦ 🧠 ✦ 🌷</div><h1>Two-minute brain break</h1><p class="sub">Match each expression to its meaning aloud or on scratch paper. This is retrieval practice—not a graded assessment.</p></section><section class="card"><div class="matchGrid">${cards.map(([a,b])=>`<div class="formula"><b>${a}</b><span>${b}</span></div>`).join('')}</div><button class="btn" onclick="go('modules')">Back to my pathway →</button></section>`)}
function certificate(){if(!S.post){go('home');return}let growth=S.diag?S.post.score-S.diag.score:0;shell(`<section class="certificate card"><div class="certBorder"><div class="confetti"> 🌷 ✦</div><div class="eyebrow">CERTIFICATE OF COMPLETION</div><h1>ACT Mastery Pathway</h1><p>This certifies that</p><div class="certName">${esc(S.name||'Student')}</div><p>completed the ACT Math preparation curriculum, demonstrated mastery across all <b>15 subtopics</b>, and completed the post-assessment.</p><div class="certStats"><span>Diagnostic <b>${S.diag?.score??'—'}/45</b></span><span>Post <b>${S.post.score}/45</b></span><span>Growth <b>${growth>=0?'+':''}${growth}</b></span></div><p class="tiny">Completed ${new Date(S.post.date).toLocaleDateString()} • Instructional curriculum; not an official ACT score report.</p></div><div class="row no-print"><button class="btn" onclick="window.print()">Print certificate</button><button class="btn secondary" onclick="report()">View mastery report</button></div></section>`)}
function showDataTools(){shell(`<section class="card"><h1>Save / load student progress</h1><p class="sub">GitHub Pages is a static host, so this version stores progress in this browser. Exporting creates a portable text backup students can save; importing restores it on another device.</p><div class="row"><button class="btn" onclick="exportData()">Export progress</button><button class="btn secondary" onclick="document.querySelector('#imp').click()">Import progress</button><input id="imp" type="file" accept="application/json" hidden onchange="importData(this.files[0])"><button class="btn secondary" onclick="resetData()">Reset</button></div></section>`)}
function exportData(){let b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`act-math-progress-${(S.name||'student').replace(/\W+/g,'-')}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(f){let r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);save();go('home')}catch(e){alert('That file could not be read.')}};r.readAsText(f)}
function resetData(){
  if(!confirm('Reset all student progress on this browser? This cannot be undone.')) return;
  // Clear every key created by current and earlier ACT Mastery/Math Pathways builds.
  try {
    Object.keys(localStorage).forEach(k=>{
      const n=k.toLowerCase();
      if(n.includes('actmasterypathway') || n.includes('actmathpathways') || n.includes('act-math') || n.includes('act_math')) localStorage.removeItem(k);
    });
    [KEY,...OLD_KEYS].forEach(k=>localStorage.removeItem(k));
    sessionStorage.clear();
  } catch(e) {}
  // Replace in-memory state too, so reset works even if storage/reload is cached or blocked.
  S={name:'',view:'home',diag:null,mastered:{},module:{},post:null,seed:11,achievements:{},bookmarks:[],activity:[],settings:{reducedMotion:false}};
  // Do not save here: a truly fresh visit should have no progress record until the student acts.
  render();
  alert('Progress has been reset.');
}
function render(){clearInterval(timerHandle);if(S.view==='modules')modules();else if(S.view==='module'&&S.current)renderModule();else if(S.view==='course')courseMap();else if(S.view==='instructor'&&sessionStorage.getItem('ampStaff')==='1')instructorView();else home()}
render();
